spring.application.name=SpringJdbc
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_jdbc
spring.datasource.username=postgres
spring.datasource.password=LocalPostgres123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true


